### ISSUE TITLE
Tracking forecasting paradigms refactor

### ISSUE THREAD

**Issue by zhangzw16** [zhangzw16/Tensor-Time-Series#1]
![image](https://github.com/user-attachments/assets/58d2d9c2-bbfd-4054-8349-08bf4082cc97)

**Comment by zhangzw16** [comment]
There are three main tasks now:

```
Task1: MTS_Task
Pram:
    - his_len
    - pred_len
    - data_mode: (time, dim1, dim2) --> (time_series_num, time_range, dim, 1)
        + 0: (1, time, dim1*dim2, 1)
        + 1: (dim1, time, dim2, 1)
        + 2: (dim2, time, dim1, 1)
    - batch_size
    - project_name
    - dataset_list
    - output_dir
Output:
    - log file saved in 'output_dir/project_name/log/xxxx.yaml'
    - checkpoints saved in 'output_dir/project_name/checkpoints/task_id/model.pth'
    - model_config snapshot saved in 'output_dir/project_name/checkpoints/task_id/configs.yml'
```

```
Task2: TTS_Task
Param:
    - his_len
    - pred_len
    - data_mode: (time, dim1, dim2) 
        + 0: (time, dim1, dim2)
        + 1: (time, dim2, dim1)
        + 2: (time, dim1*dim2, 1)
    - batch_size
    - project_name
    - dataset_list
    - output_dir
    - graph_init is 'pearson' in this task.
Output:
    - log file saved in 'output_dir/project_name/log/xxxx.yaml'
    - checkpoints saved in 'output_dir/project_name/checkpoints/task_id/model.pth'
    - model_config snapshot saved in 'output_dir/project_name/checkpoints/task_id/configs.yml'
```

```
Task3: GraphTask-Prior
    - only for prior graph tensor model
    - to test which graph initialization is better
Param:
    - his_len
    - pred_len
    - data_mode: the same as 'TTS_Task'
    - batch_size
    - project_name
    - dataset_list
    - output_dir
    - graph_init: ['inverse_pearson', 'random']
Output:
    - log file saved in 'output_dir/project_name/log/xxxx.yaml'
    - checkpoints saved in 'output_dir/project_name/checkpoints/task_id/model.pth'
    - model_config snapshot saved in 'output_dir/project_name/checkpoints/task_id/configs.yml'
```
